# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

php:
  - 5.5

script: phpunit --configuration phpunit.xml --coverage-text

notifications:
  email: "brice.laurencin@gmail.com"